//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.MainEventToCustomers = new HashSet<MainEventToCustomer>();
        }
    
        public string Gmail { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<MainEventToCustomer> MainEventToCustomers { get; set; }
    }
}
