//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Net.Mime;

    public partial class Image
    {
        public int Id { get; set; }
        public string Path { get; set; }
    
        public virtual MainEvent MainEvent { get; set; }

        public static List<MediaTypeNames.Image> AddImageToList(MediaTypeNames.Image img)
        {
            throw new NotImplementedException();
        }
    }
}
