//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainEventToCustomer
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public string IdCustomer { get; set; }
        public bool Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MainEvent MainEvent { get; set; }
    }
}
