//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainEvent
    {
        public MainEvent()
        {
            this.MainEventToCustomers = new HashSet<MainEventToCustomer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
        public int NumOfParticipance { get; set; }
        public int CostPerParticipance { get; set; }
        public double EventCost { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public string Gender { get; set; }
        public string ImagePath { get; set; }

        public virtual ICollection<MainEventToCustomer> MainEventToCustomers { get; set; }
        public virtual Speach Speach { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
