//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommunityCenterDBEntities : DbContext
    {
        public CommunityCenterDBEntities()
            : base("name=CommunityCenterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<MainEvent> MainEvents { get; set; }
        public DbSet<MainEventToCustomer> MainEventToCustomers { get; set; }
        public DbSet<Maneger> Manegers { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Speach> Speaches { get; set; }
        public DbSet<Trip> Trips { get; set; }
    }
}
