//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public Salary()
        {
            this.Manegers = new HashSet<Maneger>();
        }
    
        public double Price { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> Hour { get; set; }
    
        public virtual ICollection<Maneger> Manegers { get; set; }
    }
}
