//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public string LeavingTime { get; set; }
        public string ReturnTime { get; set; }
        public string Location { get; set; }
        public int EventId { get; set; }
    
        public virtual MainEvent MainEvent { get; set; }
    }
}
